# Generated by Django 5.0.3 on 2024-06-09 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_rename_userdetailsmodel_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdetails',
        ),
    ]
