# Generated by Django 5.0.3 on 2024-06-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='college_name',
            field=models.CharField(max_length=50),
        ),
    ]
