# Generated by Django 5.0.3 on 2024-06-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_alter_userdetails_college_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='roll_no',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='college_name',
            new_name='higherqualification',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='job',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='phone',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
