# Generated by Django 5.0.3 on 2024-06-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_rename_roll_no_userdetails_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdetails',
        ),
    ]
