# Generated by Django 5.0.3 on 2024-06-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(upload_to='')),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('book_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('available_copies', models.IntegerField()),
            ],
        ),
    ]
