# Generated by Django 5.0.3 on 2024-06-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_bookmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='available_copies',
        ),
    ]
