# Generated by Django 5.0.3 on 2024-06-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0010_remove_bookmodel_available_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='available_copies',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
