# Generated by Django 5.0.3 on 2024-06-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0011_bookmodel_available_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='book_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
