# Generated by Django 5.0.3 on 2024-06-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0013_bookmodel_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='ISBN',
        ),
    ]
