# Generated by Django 5.0.3 on 2024-06-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0015_bookrequestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
