# Generated by Django 5.0.3 on 2024-06-12 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0016_userdetails_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField()),
                ('fine', models.IntegerField(default=0)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.bookrequestmodel')),
            ],
        ),
    ]
