# Generated by Django 5.0.3 on 2024-06-12 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0017_acceptedbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedBooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('requested_date', models.DateTimeField()),
                ('accepted_date', models.DateTimeField(auto_now_add=True)),
                ('fine', models.IntegerField(default=0)),
                ('return_date', models.DateTimeField()),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.userdetails')),
            ],
        ),
    ]
