# Generated by Django 5.0.3 on 2024-06-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0018_acceptedbooksmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='genre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
